version: '3'
services:
  scheduler:
    image: daskdev/dask
    command: ["dask-scheduler"]
    ports:
      - "8786:8786"
      - "8787:8787"

  worker:
    image: daskdev/dask
    command: [
      "dask-worker",
      "tcp://scheduler:8786"
    ]
    depends_on:
      - scheduler

  notebook:
    image: daskdev/dask-notebook
    depends_on:
      - scheduler
      - worker
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"

