version: '3'
services:
  scheduler:
    image: daskdev/dask
    command: ["dask-scheduler"]
    ports:
      - "8786:8786"
      - "8787:8787"
    env_file:
      - datastore/.env
      - postgres/.env
    depends_on:
      - db
      - datastore

  worker:
    image: daskdev/dask
    command: [
      "dask-worker",
      "tcp://scheduler:8786"
    ]
    env_file:
      - datastore/.env
      - postgres/.env
    depends_on:
      - scheduler

  notebook:
    image: daskdev/dask-notebook
    depends_on:
      - scheduler
      - db
      - datastore
    ports:
      - "8888:8888"

    env_file:
      - datastore/.env
      - postgres/.env
    environment:
      -

  datastore:
    image: minio/minio
    command: [
      "server",
      "/datastore"
    ]
    env_file:
      - datastore/.env
    volumes:
      - ./datastore:/datastore
    ports:
      - "9000:9000"

  db:
    image: mdillon/postgis
    env_file:
      - postgres/.env
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/datastore

  db_admin:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
