version: '3'

services:
  dagster:
    build: dagster
    ports:
      - "3000:3000"
    depends_on:
      - dask-scheduler
      - minio
      - postgres
    volumes:
      - ./dagster:/dagster
    env_file:
      - minio/.env
      - postgres/.env

  dask-scheduler:
    image: daskdev/dask
    command: ["dask-scheduler"]
    ports:
      - "8786:8786"
      - "8787:8787"
    env_file:
      - minio/.env
      - postgres/.env
    depends_on:
      - minio
      - postgres

  dask-worker:
    image: daskdev/dask
    command: [
      "dask-worker",
      "tcp://scheduler:8786"
    ]
    env_file:
      - minio/.env
      - postgres/.env
    depends_on:
      - dask-scheduler

  minio:
    image: minio/minio
    command: [
      "server",
      "/datastore"
    ]
    env_file:
      - minio/.env
    volumes:
      - ./minio:/datastore
    ports:
      - "9000:9000"

  postgres:
    image: mdillon/postgis
    env_file:
      - postgres/.env
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
